const defaultBanner = 'Rue.js - The Compiler Framework For Native DOM'

// generated by the following code:
//
// require('gradient-string')([
//   { color: '#42d392', pos: 0 },
//   { color: '#42d392', pos: 0.1 },
//   { color: '#647eff', pos: 1 }
// ])('Rue.js - The Compiler Framework For Native DOM'))
//
// Use the output directly here to keep the bundle small.
const gradientBanner =
  '\x1B[38;2;66;211;146mR\x1B[39m\x1B[38;2;66;211;146mu\x1B[39m\x1B[38;2;66;211;146me\x1B[39m\x1B[38;2;66;211;146m.\x1B[39m\x1B[38;2;66;211;146mj\x1B[39m\x1B[38;2;67;209;149ms\x1B[39m \x1B[38;2;68;206;152m-\x1B[39m \x1B[38;2;69;204;156mT\x1B[39m\x1B[38;2;70;201;159mh\x1B[39m\x1B[38;2;71;199;162me\x1B[39m \x1B[38;2;72;196;165mC\x1B[39m\x1B[38;2;73;194;168mo\x1B[39m\x1B[38;2;74;191;172mm\x1B[39m\x1B[38;2;75;189;175mp\x1B[39m\x1B[38;2;76;186;178mi\x1B[39m\x1B[38;2;77;184;181ml\x1B[39m\x1B[38;2;78;181;184me\x1B[39m\x1B[38;2;79;179;188mr\x1B[39m \x1B[38;2;80;176;191mF\x1B[39m\x1B[38;2;81;174;194mr\x1B[39m\x1B[38;2;82;171;197ma\x1B[39m\x1B[38;2;83;169;201mm\x1B[39m\x1B[38;2;84;166;204me\x1B[39m\x1B[38;2;85;164;207mw\x1B[39m\x1B[38;2;86;161;210mo\x1B[39m\x1B[38;2;87;159;213mr\x1B[39m\x1B[38;2;88;156;217mk\x1B[39m \x1B[38;2;89;154;220mF\x1B[39m\x1B[38;2;90;151;223mo\x1B[39m\x1B[38;2;91;149;226mr\x1B[39m \x1B[38;2;92;146;229mN\x1B[39m\x1B[38;2;93;144;233ma\x1B[39m\x1B[38;2;94;141;236mt\x1B[39m\x1B[38;2;95;139;239mi\x1B[39m\x1B[38;2;96;136;242mv\x1B[39m\x1B[38;2;97;134;245me\x1B[39m \x1B[38;2;98;131;249mD\x1B[39m\x1B[38;2;99;129;252mO\x1B[39m\x1B[38;2;100;126;255mM\x1B[39m'

export { defaultBanner, gradientBanner }
