const defaultBanner = 'Rue.js - The Wasm Framework For Native DOM'

// generated by the following code:
//
// require('gradient-string')([
//   { color: '#42d392', pos: 0 },
//   { color: '#42d392', pos: 0.1 },
//   { color: '#647eff', pos: 1 }
// ])('Rue.js - The Wasm Framework For Native DOM'))
//
// Use the output directly here to keep the bundle small.
const gradientBanner =
  '\x1B[38;2;66;211;146mR\x1B[39m\x1B[38;2;66;211;146mu\x1B[39m\x1B[38;2;66;211;146me\x1B[39m\x1B[38;2;66;211;146m.\x1B[39m\x1B[38;2;66;211;146mj\x1B[39m\x1B[38;2;67;209;149ms\x1B[39m\x1B[38;2;68;207;152m \x1B[39m\x1B[38;2;69;204;155m-\x1B[39m\x1B[38;2;70;202;158m \x1B[39m\x1B[38;2;71;200;160mT\x1B[39m\x1B[38;2;71;197;163mh\x1B[39m\x1B[38;2;72;195;166me\x1B[39m\x1B[38;2;73;193;169m \x1B[39m\x1B[38;2;74;190;172mW\x1B[39m\x1B[38;2;75;188;175ma\x1B[39m\x1B[38;2;76;186;178ms\x1B[39m\x1B[38;2;77;184;181mm\x1B[39m\x1B[38;2;78;181;184m \x1B[39m\x1B[38;2;79;179;187mF\x1B[39m\x1B[38;2;80;177;190mr\x1B[39m\x1B[38;2;81;174;193ma\x1B[39m\x1B[38;2;82;172;196mm\x1B[39m\x1B[38;2;82;170;199me\x1B[39m\x1B[38;2;83;167;202mw\x1B[39m\x1B[38;2;84;165;205mo\x1B[39m\x1B[38;2;85;163;208mr\x1B[39m\x1B[38;2;86;161;211mk\x1B[39m\x1B[38;2;87;158;214m \x1B[39m\x1B[38;2;88;156;217mF\x1B[39m\x1B[38;2;89;154;220mo\x1B[39m\x1B[38;2;90;151;223mr\x1B[39m\x1B[38;2;91;149;225m \x1B[39m\x1B[38;2;92;147;228mN\x1B[39m\x1B[38;2;93;144;231ma\x1B[39m\x1B[38;2;94;142;234mt\x1B[39m\x1B[38;2;94;140;237mi\x1B[39m\x1B[38;2;95;138;240mv\x1B[39m\x1B[38;2;96;135;243me\x1B[39m\x1B[38;2;97;133;246m \x1B[39m\x1B[38;2;98;131;249mD\x1B[39m\x1B[38;2;99;128;252mO\x1B[39m\x1B[38;2;100;126;255mM\x1B[39m'

export { defaultBanner, gradientBanner }
